### ISSUE TITLE
楼主，您好，仔细看了一下这个单点登录，感觉考虑的问题很全面，但看了代码，也有缺陷

### ISSUE THREAD

**Issue by qiuqingpo** [weixiaolong325/SSO.Demo.SSO#1]
既然是单点登录，为什么不把登录，验证，缓存都统一放在一个项目里，现在是每个子系统也都写一份验证和缓存（虽然仅仅是跳转），挺冗余的，我觉得你完全可以放在一个项目里去做呀。你直接都Js跳转登录中心验证不就好了

**Comment by weixiaolong325** [comment]
> 既然是单点登录，为什么不把登录，验证，缓存都统一放在一个项目里，现在是每个子系统也都写一份验证和缓存（虽然仅仅是跳转），挺冗余的，我觉得你完全可以放在一个项目里去做呀。你直接都Js跳转登录中心验证不就好了

哥们，我不太明白你最后说的js跳转登录中心验证是指验证哪个？
子系统有局部会话就不需要跳转了呀，不然每次刷新页面都跳一次登录中心又跳回来，跳转毕竟在视觉上还是有一点影响的，页面加载那个验证是为了模拟普通请求时的token校验。

**Comment by qiuqingpo** [comment]
/Account/GetUserInfo

我是觉得你所有的业务web ，都应该直接调用登录验证中心的getuserinfo，真的不必每个都再写一次登录验证的逻辑。虽然你也仅仅就是跳转

**Comment by qiuqingpo** [comment]
登录验证中心就是你的SSO.Demo.SSO这个项目，SSO.Demo.Web1与SSO.Demo.Web2其实都是可以直接调用这个的，真的没有必须在web1和web2里再写一次AccountController.虽然你也仅仅就是跳转，是为了好跨域好吗

**Comment by weixiaolong325** [comment]
确实是可以直接调SSO根据 code换token的，通过子系统获取的目的有2个。
1.就是你所说的好跨域问题，这个是次要的。
2.主要是为了安全性。为了证明这个token的来源是sso，不是别的假冒的。如果前端直接调SSO获取，第一次使用时也要请求SSO验证这个token来源是SSO的，然后再做缓存，都是要请求一次SSO的。
